[tool.poetry]
name = "enigma"
version = "0.1.0"
description = "Enigma emulator"
authors = ["Luke Shiner <luke@lukeshiner.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/lukeshiner/enigma"
repository = "https://github.com/lukeshiner/enigma"

keywords = ["enigma", "cryptography"]

classifiers = [
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Natural Language :: English",
    "Topic :: Utilities",
    "Topic :: Other/Nonlisted Topic",
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
flake8 = "^3.7.9"
black = {version = "^19.10b0", allow-prereleases = true}
pydocstyle = "^5.0.2"
coveralls = "^1.10.0"
pytest-cov = "^2.8.1"
isort = "^4.3.21"
mypy = "^0.790"

[tool.pytest.core]
addopts = "--cov=.--cov-report=html"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

